[http_service]
    internal_port = 9001
    force_https = true
    auto_stop_machines = true
    auto_start_machines = true
    min_machines_running = 0
    processes = ["app"]
[mounts]
    source = "data"
    destination = "/data"
