name: moja_pro
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Assets
  flutter_localizations:
    sdk: flutter
  pattern_formatter:
  cupertino_icons:
  equatable:
  go_router:
  intl:
  # Widgets
  listenable_tools:
  widget_tools:
  maplibre_gl:
  lottie:
  # Services
  firebase_messaging:
  permission_handler:
  extended_image:
  firebase_core:
  service_tools:
  firebase_auth:
  hive_flutter:
  image_picker:
  image_editor:
  url_launcher:
  share_plus:
  hive:
  dio:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter_gen:
  output: lib/screen/widget/service/schema/assets/
  line_length: 80

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/files/
    - assets/images/
  fonts:
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/HelveticaNeue.ttc
    - family: FiraGO
      fonts:
        - asset: assets/fonts/FiraGO.ttf
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa.ttf
    - family: NeueHaasGrotesk
      fonts:
        - asset: assets/fonts/NeueHaasGrotesk.otf
    - family: Calibre
      fonts:
        - asset: assets/fonts/Calibre.otf
