// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_auth/firebase_auth.dart' show FirebaseAuth;
import 'package:firebase_storage/firebase_storage.dart' show FirebaseStorage;
import 'package:firebase_messaging/firebase_messaging.dart' show FirebaseMessaging;
import 'package:firebase_core/firebase_core.dart' show Firebase, FirebaseApp, FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class FirebaseConfig {
  const FirebaseConfig._();

  static FirebaseAuth get firebaseAuth => FirebaseAuth.instanceFor(app: app);
  static FirebaseStorage get firebaseStorage => FirebaseStorage.instanceFor(app: app);
  static FirebaseMessaging get firebaseMessaging => FirebaseMessaging.instance;

  static FirebaseApp? _app;
  static FirebaseApp get app => _app!;

  static Future<void> development() async {
    _app ??= await Firebase.initializeApp(
      name: 'development',
      options: _currentPlatform,
    );
  }

  static Future<void> production() async {
    _app ??= await Firebase.initializeApp(
      options: _currentPlatform,
    );
  }

  static FirebaseOptions get _currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return _android;
      case TargetPlatform.iOS:
        return _ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions _android = FirebaseOptions(
    apiKey: 'AIzaSyDrVgU4jsdjly2_vN17-MLgZS3FpRq1Oao',
    appId: '1:73497335498:android:25fb78348a3302637a4633',
    messagingSenderId: '73497335498',
    projectId: 'moja-project',
    storageBucket: 'moja-project.appspot.com',
  );

  static const FirebaseOptions _ios = FirebaseOptions(
    apiKey: 'AIzaSyCmOtdB_xflsMbrc6dUnWLA8i1ODT9i_IM',
    appId: '1:73497335498:ios:77dee701af07353f7a4633',
    messagingSenderId: '73497335498',
    projectId: 'moja-project',
    storageBucket: 'moja-project.appspot.com',
    iosBundleId: 'com.moja.mojapro',
  );
}
